### ISSUE TITLE
Problema ao instalar dependencias

### ISSUE THREAD

**Issue by tassioalves** [Raisess/insta-bot#1]
C:\Users\t\Documents\insta-bot\node_modules\puppeteer\install.js:175
            } catch {
                    ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm WARN insta-bot@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@3.1.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@3.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\t\AppData\Roaming\npm-cache\_logs\2020-06-27T01_10_19_997Z-debug.log

**Comment by Raisess** [comment]
Esse problema provavelmente pode estar relacionado a versão do nodejs, ou a instalação do puppeteer está dando conflito com outra versão, tente remover as dependências manualmente **npm remove puppeteer && npm remove readline-sync** e dps instale novamente **npm i --save puppeteer && npm i --save readline-sync**.
